[package]
name = "rust6502lexer"
version = "0.1.0"
authors = ["mark chaitin <mchaitin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"
hex = "0.4.2"
lazy_static = "1.4.0"