[package]
name = "rust6502lexer"
version = "0.1.0"
authors = ["mark chaitin <mchaitin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flexi_logger = "0.15.12"
log = "0.4.11"